version: '3.8'

services:
  camera-app:
    image: javohirgo/smile-mini-pc-app:latest  # Use image, not build path here
    container_name: camera-streaming-app
    restart: unless-stopped

    # Uncomment if you're accessing physical cameras
    # devices:
    #   - /dev/video0:/dev/video0
    #   - /dev/video1:/dev/video1

    privileged: false
    network_mode: host  # Required for RTSP, discovery, WebSocket performance

    ports:
      - "8765:8765"

    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./videos:/app/videos
      - ./temp_videos:/app/temp_videos

    environment:
      - PYTHONPATH=/app
      - HOST_MAC=${HOST_MAC}
      - OPENCV_VIDEOIO_PRIORITY_MSMF=0
      - CUDA_VISIBLE_DEVICES=""
      - OPENCV_DNN_BACKEND=0
      - MPLBACKEND=Agg
      - LIBGL_ALWAYS_INDIRECT=1

      # Application-specific
      - ENABLE_WEBSOCKET=true
      - WEBSOCKET_PORT=8765
      - WEBSOCKET_QUALITY=100
      - WEBSOCKET_MAX_FPS=30
      - VIDEO_GENERATION_ENABLED=true
      - VIDEO_TRIGGER_EMOTIONS=upset,smile,normal
      - FFMPEG_ENABLED=true
      - OPENCV_FFMPEG_CAPTURE_OPTIONS=protocol_whitelist;file,rtp,udp

    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID

    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'
